// Code generated by Slice Machine. DO NOT EDIT.

import Features from './Features';
import Hero from './Hero';
import ImageAndText from './ImageAndText';
import Text from './Text';

export {
	Features,
	Hero,
	ImageAndText,
	Text,
};

export const components = {
	features: Features,
	hero: Hero,
	image_and_text: ImageAndText,
	text: Text,
};
